### ISSUE TITLE
import UMLS id mapping to chemicals/drugs

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#10]
UMLS provide IDs for many biological entity types, including chemicals and drugs:

https://www.nlm.nih.gov/research/umls/

Similar to this UMLS <-> gene mapping for MyGene.info:
https://github.com/biothings/mygene.info/tree/master/src/dataload/sources/umls

, we can import the mapping of UMLS <-> chemicals/drugs into MyChem.info.

**Comment by kevinxin90** [comment]
This needs to be a higher priority. The Semmed API only use UMLS ids to represent chemicals. But we don't have UMLS ID -> other chemical ID mapping yet.

**Comment by andrewsu** [comment]
Closing this ticket -- it appears that we have 346k mappings to UMLS in mychem.info...

http://mychem.info/v1/query?q=_exists_:umls.cui

```
{
"took": 7,
"total": 346185,
"max_score": 1,
"hits": [...]
}
```
