### ISSUE TITLE
default query fields

### ISSUE THREAD

**Issue by andrewsu** [biothings/mychem.info#11]
I have a vague recollection of mentioning this issue before, but I forget the response.  So just adding it here.

I was expecting this query:
http://mychem.info/v1/query?q=imatinib

to return a superset of records relative to this fielded query:
http://mychem.info/v1/query?q=drugbank.name%3Aimatinib

But the first query currently returns no results.  I'm guessing this has to do with what fields are indexed by default.  I'll leave it you guys to decide whether this is the desired behavior or something to be changed....

**Comment by veleritas** [comment]
Apparently searching for all fields isn't defined yet for mychem

**Comment by greg-k-taylor** [comment]
To be consistent with other APIs, such as 'mygene.info' the above query should return results.  I can look into a fix for this issue - could someone assign the issue to me?

Here is a related 'mygene.info' query that returns results - all fields are returned.
http://mygene.info/v3/query?q=CDK2

**Comment by sirloon** [comment]
added include_in_all = true by default, so all fields are searched when non-fielded queries are used (eg. http://mychem.info/v1/query?q=imatinib). This will be reviewed when migrating to ES6 when include_in_all has to explicit for all fields.
Note: current index has grown 10%+ , from 84GiB to 94GiB

**Comment by andrewsu** [comment]
Not sure if we've hit practical limitations in index size, but looks like CHEMBL IDs are not indexed.  For example, I was expecting http://mychem.info/v1/query?q=CHEMBL941 to match http://mychem.info/v1/chem/KTUFNOKKBVMGRW-UHFFFAOYSA-N (but currently I need to explicitly specify the field: http://mychem.info/v1/query?q=chembl.molecule_chembl_id:CHEMBL941)

**Comment by kevinxin90** [comment]
Fixed in 139e1a600f9144b737f1bfa5dc5bc7a452988446. Should be available in next MyChem.info release.

**Comment by ravila4** [comment]
This issue is still open because `chembl.molecule_chembl_id` is not searched by default. It should be an easy fix, just need to add `"copy_to": [ "all" ]` to the hard-coded mappping:

https://github.com/biothings/mychem.info/blob/master/src/hub/dataload/sources/chembl/chembl_upload.py#L260-L263

**Comment by ravila4** [comment]
Closing this because the latest data release fixes this issue.
I verified that queries like http://mychem.info/v1/query?q=CHEMBL941  work now.
