### ISSUE TITLE
Fix PubChem collection indexing error

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#113]
Currently, this `post_update_data` step fails with a MongoDB indexing error:

https://github.com/biothings/mychem.info/blob/1f1d79aec331c8bb65a6129d0c9c4e11220a7354/src/hub/dataload/sources/pubchem/pubchem_upload.py#L41-L47

Either this error for default single-field indexing:
```
ERROR -- failed [steps=data,post,master,clean]: WiredTigerIndex::insert: key too large to index, failing  1576 { : "InChI=1S/C157H257N3O82P2/c1-66(2)32-22-33-67(3)34-23-35-68(4)36-24-37-69(5)38-25-39-70(6)40-26-41-71(7)42-27-43-72(8)44-28-45-73(9)46-29-47-74(10)48-3..." }
```

or this error if use hashed index type:

```
ERROR -- failed: Error: hashed indexes do not currently support array values. Found array at path: pubchem
```

Short-term solution is to figure out a way to make the indexing through (skipping problematic docs is fine).

Longer-term solution is to compute "Inchikey" directly from "inchi" string, that way, there is no need to index "inchi" field.

**Comment by newgene** [comment]
For the short-term solution, there is an option of "partial index", but "partial index" (via partialFilterExpression indexing parameter) has no support of a filter query with `$where` (to filter based on string length), only simple value comparison, existence-checking etc are supported (partial index doc [here](https://docs.mongodb.com/manual/core/index-partial/#create-a-partial-index)).

One solution is to pre-create a new field like `long_inchi_str: true` to flag the problematic doc (inchi string >1024 bytes), we can then use it in partial index.

For hashed indexing, we can use a field like `dup_inchi: true` to flag and skip.

@ravila4 can you get the total number of skipped pubchem docs in both cases? We should pick a way with less impacted docs.

**Comment by newgene** [comment]
About computing InchiKey from Inchi:

* https://www.rdkit.org/docs/source/rdkit.Chem.inchi.html#rdkit.Chem.inchi.InchiToInchiKey
* https://github.com/metamolecular/inchi/blob/0fc7adc58d4ff1c481b26e0de53cc8a404c3d381/INCHI_API/demos/python_sample/yapyinchi.py#L149 (this looks like using c-library from Inchi Trust)
* Also a pure python version mentioned here: https://bioinformatics.stackexchange.com/questions/2438/how-to-interconvert-inchi-and-inchikey

**Comment by ravila4** [comment]
An easier way to skip documents with failed indexes might be to set failIndexKeyTooLong to true:  https://docs.mongodb.com/v3.2/reference/parameters/#param.failIndexKeyTooLong  The downside is that is a server configuration, and it would apply to all collections.

**Comment by ravila4** [comment]
For computing inchikeys from inchi, RDKit seems to be pretty fast and widely used, it also uses C libraries in the back-end.

**Comment by newgene** [comment]
Looks like `failIndexKeyTooLong` is now removed in newer version of MongoDB, also not recommended to use:

https://docs.mongodb.com/manual/reference/parameters/#mongodb-parameter-param.failIndexKeyTooLong

**Comment by newgene** [comment]
By upgrading backend MongoDB server from `4.0.x` to `5.0.x`, the [index key limit] (https://docs.mongodb.com/manual/reference/limits/#mongodb-limit-Index-Key-Limit) (was <=1024 bytes) is now removed (since `v4.2`), so the normal indexing on `pubchem.inchi` field is now working nicely.
