### ISSUE TITLE
Update PubChemDumper with the new folder sync feature from BioThings

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#117]
Ref: https://github.com/biothings/biothings.api/issues/173

The corresponding changes are required at [PubChemDumper](https://github.com/biothings/mychem.info/blob/master/src/hub/dataload/sources/pubchem/pubchem_dump.py) side to use this new feature.

**Comment by newgene** [comment]
also cc'ing @zcqian

**Comment by zcqian** [comment]
Already implemented in https://github.com/biothings/mychem.info/commit/b865d9cead249e44a22b79fc2f47562a694a3b48
