### ISSUE TITLE
issues with MyChem mappings to rhea 

### ISSUE THREAD

**Issue by colleenXu** [biothings/mychem.info#119]
something seems odd about how MyChem deals with Rhea:

---

A:
    having chebi.xrefs.rhea is odd since the Rhea IDs are actually reactions that the various chemicals are involved in. Instead, I suggest having records under each chemical:

```
{
  _id: XXXXX,
  chebi: {}, 
  chembl: {},
  rhea: [
    {reaction_id: X},
    {reaction_id: Y}
  ]
}
```

---

B:
    unichem.rhea seems to be incorrect; its value is just the CHEBI ID rather than a Rhea Reaction ID. See how this record says that the unichem.rhea ID is 42758....this ID does not correspond to a rhea reaction with the chemical inside. Instead, 42758 seems to be the CHEBI ID for this chemical.

I would suggest something that clarifies that rhea is using the chebi IDs for chemicals, but there are separate rhea reaction IDs that are something different

**Comment by colleenXu** [comment]
Discussion with Ricardo was happening here: https://github.com/SmartAPI/smartAPI/issues/123#issuecomment-924197340

**Comment by ravila4** [comment]
Thanks @colleenXu. If we are creating a new Rhea top-level object, I see two possibilities. Either we simply modify the current CHEBI parser to transform the data in the way that you specified, or perhaps we may want to create a new data plugin specifically for Rhea, containing information like the one shown in https://www.rhea-db.org/rhea/?query=CHEBI:42758&format=json. I think some of the Rhea metadata, like the comment and equation, can actually be quite useful.

**Comment by colleenXu** [comment]
yes, I thought some of the rhea information was very interesting. It wasn't clear to me where the current rhea info is coming from, and whether it's being transformed in a way that makes it clear to the user what it's doing. 

To reiterate: 
- these chebi.xrefs make it sound like the chemical == the rhea reaction ID, which is incorrect
- the unichem.rhea make it sound like the chemical has this ID as a rhea ID (which isn't quite right, it's the chebi ID that rhea can then recognize).

**Comment by ravila4** [comment]
On the other hand, I see the same issue potentially exists for chebi.xrefs.reactome, where the ID refers to a reaction which has many potential participants. I don't know the details of how these x-refs are being processed downstream in BTE, but I think it's also worth looking into.

**Comment by colleenXu** [comment]
ah yeah, that would be another example...

**Comment by colleenXu** [comment]
I suggest closing this @ravila4 since I've seen on the CHEBI website that this is just how it seems that this is just how CHEBI structures its xrefs - they are to "other bioentities" rather than to "synonymous IDs"...

I can work with this, I just found it a bit confusing.
