### ISSUE TITLE
Aeolus 'indications' field not being indexed

### ISSUE THREAD

**Issue by ravila4** [biothings/mychem.info#121]
The `aeolus.indications` field is not indexed because the field is missing from the hard-coded mapping:

https://github.com/biothings/mychem.info/blob/4fffe1348e5a665be2e07323379700d51a437976/src/hub/dataload/sources/aeolus/aeolus_upload.py#L38-L127

**Comment by colleenXu** [comment]
tagging myself @colleenXu for finding it :P

**Comment by ravila4** [comment]
Hi Colleen, I updated the mapping in [this branch](https://github.com/biothings/mychem.info/blob/bug-121-fix-aeolus-mapping/src/hub/dataload/sources/aeolus/aeolus_upload.py). There are actually a couple of changes in the datasource compared to the previous version, as you can see in this diff:

![Screenshot from 2021-11-11 14-15-52](https://user-images.githubusercontent.com/9020496/141376789-8044b2d8-900c-46c5-a94c-f3613eafca1d.png)

Both "indications", "drug_rxcui" are new, and  "drug_vocab", "drug_code", and "relationships" were removed. I'm going to check the data so see why it is that they are missing (whether the data changed, or it's a bug in the parser).

**Comment by ravila4** [comment]
Related to https://github.com/biothings/mychem.info/issues/70

**Comment by ravila4** [comment]
The aeolus mapping was manually updated in the mondodb `mychem_hubdb.src_master` collection.

**Comment by colleenXu** [comment]
okay! My queries are now working.
