### ISSUE TITLE
Drugcentral fields with spaces in their names

### ISSUE THREAD

**Issue by ravila4** [biothings/mychem.info#122]
As a convention, field names should not have spaces because they are hard to query.

Current problematic fields include:

```
drugcentral.drug_use.off-label use
drugcentral.drug_use.reduce risk
drugcentral.drug_use.symptomatic treatment
```

**Comment by colleenXu** [comment]
tagging myself @colleenXu for finding it :P

**Comment by ravila4** [comment]
@colleenXu The latest data release fixes this issue. You can see the changelog here:
https://github.com/biothings/mychem.info/pull/126
