### ISSUE TITLE
extensive duplication in drugbank.mixtures

### ISSUE THREAD

**Issue by andrewsu** [biothings/mychem.info#13]
for example, see http://mychem.info/v1/chem/KTUFNOKKBVMGRW-UHFFFAOYSA-N?fields=drugbank,drugcentral

screenshot:
![2017-12-21_9-38-04](https://user-images.githubusercontent.com/2635409/34267707-b23f55ac-e632-11e7-9863-38a9799baaea.png)

**Comment by newgene** [comment]
This seems not being solved in the recent data release. More examples here:

http://mychem.info/v1/query?q=_exists_:drugbank.mixtures&fields=drugbank.mixtures,drugbank.name

@greg-k-taylor

**Comment by greg-k-taylor** [comment]
This patch may solve the problem.  It appears inefficient (during the parsing step) but removes duplicates.  Below is a link to the patch and a list of a few documents without duplicates.  I spot checked DB00007, DB00008, and DB00009 which have duplicates in the current version of mychem.info.

https://github.com/greg-k-taylor/mychem.info/commit/f294b271c58696c69ee8cd7449e7762e2070e9c0

Here is a short list of documents without duplicates (using the patch):
{ "_id" : "DB00007", "drugbank" : { "mixtures" : [ { "name" : "Lupaneta Pack", "ingredients" : [ "Leuprolide", "Norethisterone" ] } ] } }
{ "_id" : "DB00008", "drugbank" : { "mixtures" : [ { "name" : "Pegasys Rbv", "ingredients" : [ "Peginterferon alfa-2a", "Ribavirin" ] } ] } }
{ "_id" : "DB00009", "drugbank" : { "mixtures" : [ { "name" : "Lysatec RT - Pa", "ingredients" : [ "Alteplase", "Water" ] }, { "name" : "Activase RT-PA", "ingredients" : [ "Alteplase", "Water" ] }

**Comment by newgene** [comment]
Now in pull request: https://github.com/biothings/mychem.info/pull/57

**Comment by greg-k-taylor** [comment]
Pull request merged and closed.

**Comment by greg-k-taylor** [comment]
Ooops, not verified in production yet.
