### ISSUE TITLE
create scheduled update of UMLS

### ISSUE THREAD

**Issue by andrewsu** [biothings/mychem.info#130]
UMLS is a key biomedical resource for chemicals and other entities.  http://mychem.info/v1/metadata says the last update was April 2020.  According to the [release history](https://www.nlm.nih.gov/research/umls/licensedcontent/umlsarchives04.html), UMLS is updated twice a year every May and November.  We should update UMLS to the latest version, and also have some sort of automated (or semi-automated) way to triggering these updates (or at least notifying a data manager).  The relevant parser code is in https://github.com/biothings/mychem.info/tree/master/src/hub/dataload/sources/umls.  

Related issues:
* https://github.com/biothings/mygene.info/issues/124
* https://github.com/biothings/mydisease.info/issues/46

**Comment by ravila4** [comment]
The UMLS data is behind an authentication wall, so it is difficult to make an automatic data downloads. The latest update should allow the dumper to check for the latest version. If a new version found, the uploader will auto-trigger and fail with an error message that asks the maintainer to download the relevant files.

A possible alternative for automating the whole download process, could be to use the UMLS API to fetch the data using and API key: https://documentation.uts.nlm.nih.gov/rest/home.html, however this requires rewriting the parser.

**Comment by ravila4** [comment]
@andrewsu The UMLS data has been updated in the latest release, so I am closing this issue.
