### ISSUE TITLE
re-index `drugcentral.bioactivity.action_type` field as keyword, perhaps index Chembl.drug_indications.first_approval

### ISSUE THREAD

**Issue by colleenXu** [biothings/mychem.info#153]
After discussion with Chunlei (internal lab Slack [link](https://suwulab.slack.com/archives/CC19LHAF2/p1675277199077969?thread_ts=1675149235.900659&cid=CC19LHAF2)), Chunlei suggested re-indexing `drugcentral.bioactivity.action_type` field as keyword (currently it's text). This is because I was having issues with unexpected partial matches (see quoted section below, pasted from Slack). I agree that this would solve my issue and seems to make sense with the data.

I also noticed that the field Chembl.drug_indications.first_approval may not be indexed at all (not showing up in metadata/fields endpoint). Maybe it should be? However, right now, BTE doesn't need this field to be indexed. 

> I've been querying MyChem's drugcentral.bioactivity info, and I have a question: when I ask for records where drugcentral.bioactivity.action_type:"MODULATOR" , I get some that appear to be partial matches. That's unexpected to me, since I had expected an exact match. Examples from this [query](https://mychem.info/v1/query?q=drugcentral.bioactivity.action_type:%22MODULATOR%22&fields=drugcentral.bioactivity.action_type&size=1000):
> WYJAPUKIYAZSEM-RBUKOAKNSA-N: its 4 bioactivities are ALLOSTERIC MODULATOR
> GBBSUAFBMRNDJC-UHFFFAOYSA-N: its 8 bioactivities are POSITIVE MODULATOR
> LEQAKWQJCITZNK-AXHKHJLKSA-N: its 3 bioactivities are NEGATIVE MODULATOR
> This kind of thing is also happening if I query for action_type with other terms like AGONIST (entires that only have PARTIAL AGONIST will appear)

**Comment by DylanWelzel** [comment]
commit 3b70e704a32be82de7de9264e881bbb0838244b7 updates `drugcentral.bioactivity.action_type` to keyword and commit 8eb681935c6dfc6024ed249cde238604d5c59ea1 adds `chembl.drug_indications.first_approval` pending a new release.

**Comment by colleenXu** [comment]
Noting: want a quick review of drugcentral bioactivity x-bte annotation. Maybe can be updated if this field now behaves as keyword...(exact matching on modulator)?

**Comment by DylanWelzel** [comment]
These changes are now live with the new release.

**Comment by colleenXu** [comment]
Closing since the API changes are complete. Will open a different issue to update the x-bte annotation.
