### ISSUE TITLE
split ndc.pharm_classes value into a list

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#161]
https://mychem.info/v1/query?q=_exists_:ndc.pharm_classes&fields=ndc.pharm_classes

```
"pharm_classes": "Anti-Inflammatory Agents, Non-Steroidal [CS], Cyclooxygenase Inhibitors [MoA], Histamine H2 Receptor Antagonists [MoA], Histamine-2 Receptor Antagonist [EPC], Nonsteroidal Anti-inflammatory Drug [EPC]",
```
Looks like it can be split into a list of string or object (if we want to split out `CS`, `MoA` parts)

**Comment by colleenXu** [comment]
Note that I mention this field here in a potential annotation service effort https://github.com/biothings/biothings_explorer/issues/344#issuecomment-961647522

**Comment by newgene** [comment]
@VidhiKulkarni the relevant data plugin is here: 

https://github.com/biothings/mychem.info/tree/master/src/hub/dataload/sources/ndc

particularly, the [ndc_parser.py](https://github.com/biothings/mychem.info/blob/master/src/hub/dataload/sources/ndc/ndc_parser.py) file.

**Comment by DylanWelzel** [comment]
@newgene So the expected result for:
```
"pharm_classes": "Anti-Inflammatory Agents, Non-Steroidal [CS], Cyclooxygenase Inhibitors [MoA], Histamine H2 Receptor Antagonists [MoA], Histamine-2 Receptor Antagonist [EPC], Nonsteroidal Anti-inflammatory Drug [EPC]",
```
Should be:
```
    "pharm_classes": [
        "Anti-Inflammatory Agents, Non-Steroidal",
        "Cyclooxygenase Inhibitors",
        "Histamine H2 Receptor Antagonists",
        "Histamine-2 Receptor Antagonist",
        "Nonsteroidal Anti-inflammatory Drug"
    ]
```

**Comment by newgene** [comment]
@DylanWelzel can you provide the available values of the categories within the brackets, like `CS`, `MoA`, `EPC` etc.? We might consider split these values out.

**Comment by DylanWelzel** [comment]
@newgene I included the total count for each category as well
```
MoA (56950)
EPC (94522)
CS (50390)
PE (58556)
Chemical/Ingredient (510)
EXT (1620)
```

**Comment by DylanWelzel** [comment]
commit 42ff7cf8091e8efaaff92cb37afb3c95fbf688b4 fixes this issue, pending new release

**Comment by DylanWelzel** [comment]
fixed with new release
