### ISSUE TITLE
MyChem entry for "Insulin Determir" not merged correctly

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#169]
This record for "insulin determir":

https://mychem.info/v1/chem/4FT78T86XV?fields=unii

seems should be merged into this one:

https://mychem.info/v1/chem/UGOZVNFCFYTPAZ-IOXYNQHNSA-N

It should be related to how mychem's `hub.transformation` module works in this particular case.

**Comment by DylanWelzel** [comment]
fixed with #172
