### ISSUE TITLE
Include NCIT description in unii uploader

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#170]
UNII data source includes a mapping to NCIT id in `unii.ncit` field.

In this translator tool, we populated `unii.ncit_description` field based on our NCIT API at https://biothings.ncats.io/ncit on the fly, e.g.:

https://biothings.ncats.io/annotator/CHEBI:5790?fields=unii.ncit

It would be better if we could include this description field directly in MyChem.info.

**Comment by newgene** [comment]
The relevant code we populate this description field on the fly is here:

https://github.com/biothings/pending.api/blob/ac6034f52475b7e3d99a2c0fce0631de9526513a/web/handlers/annotator.py#L68-L102

which we can use in UNII parser as well.

**Comment by newgene** [comment]
also less likely, but we can confirm UNII data source does not include NCIT description first.

**Comment by DylanWelzel** [comment]
added ncit descriptions in #172
