### ISSUE TITLE
unii has a field of "display name" with the whitespace in the field

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#177]
here is an example:

```
    {
      "_id": "GKMPTIBZVGZJDN-RJLNLWLESA-N",
      "_score": 0.7955475,
      "unii": {
        "_license": "http://bit.ly/2Pg8Oo9",
        "display name": "CBP-501 ACETATE"
      }
    }
```

probably should be `display_name` instead

**Comment by DylanWelzel** [comment]
commit [#858e4faa](https://github.com/biothings/mychem.info/commit/858e4faab9cf900002c5071558c2f754a7de76e5) fixes this issue pending a new release

**Comment by DylanWelzel** [comment]
This fix is live, example:
https://mychem.info/v1/chem/GKMPTIBZVGZJDN-RJLNLWLESA-N?fields=unii
`"display_name": "CBP-501 ACETATE",`
