### ISSUE TITLE
Allow for exact match on the drug/chemical name

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#178]
An example query for `cisplatin` returns 33 hits including matches like `cisplatin complex` etc.

https://mychem.info/v1/query?q=cisplatin&fields=_id&size=50&fields=chembl.pref_name,pharmgkb.name,aeolus.drug_name,%22unii.display%20name%22,umls

while this query is correct, we should create a way to return hits only match `cisplatin` exactly, like a keyword-indexed field called `name.raw` for this purpose.

**Comment by DylanWelzel** [comment]
Feature added with #179 and currently live, examples:
https://mychem.info/v1/query?q=name.raw:%22cisplatin%22&size=50&fields=chembl.pref_name,pharmgkb.name,aeolus.drug_name,%22unii.display%20name%22,umls
https://mychem.info/v1/query?q=name:%22cisplatin%22&size=50&fields=chembl.pref_name,pharmgkb.name,aeolus.drug_name,%22unii.display%20name%22,umls
