### ISSUE TITLE
aeolus.outcomes.meddra_code is not index properly

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#24]
Sample data:

http://mychem.info/v1/query?q=_exists_:aeolus.outcomes&fields=aeolus.outcomes

this field "aeolus.outcomes.meddra_code" was labelled as "aeolus.outcomes.code" in the mapping: 

[aeolus/aeolus_upload.py#L74](https://github.com/biothings/mychem.info/blob/master/src/hub/dataload/sources/aeolus/aeolus_upload.py#L74)

should change the mapping to "meddra_code", and this query should work:

[q=aeolus.outcomes.meddra_code:10028813](http://mychem.info/v1/query?q=aeolus.outcomes.meddra_code:10028813)

**Comment by newgene** [comment]
Also does not seem "vacab" exists any more:

http://mychem.info/v1/query?q=_exists_:aeolus.outcomes.vocab&fields=aeolus.outcomes

if confirmed, can remove that field from the mapping or maybe run the inspector again to double check other aeolus fields as well.

**Comment by newgene** [comment]
@sirloon please verify if this is still an issue.

**Comment by sirloon** [comment]
@newgene meddra_code is addressed in this commit f2c51d234746bb8531a3c3c42a02854d184efdea but for vocab, there's no such data actually in the collection

**Comment by sirloon** [comment]
remove field "vocab" from mapping as it doesn't exist anymore in the data af4d9e8733dc7b9daf9c7231c3779a522a5651ef
