### ISSUE TITLE
ChEMBL cross_references should be restructured

### ISSUE THREAD

**Issue by kevinxin90** [biothings/mychem.info#27]
1. Data should be grouped based on xref_src
2. CURIEs should be converted to values if it's the standard representation by the source
Example:
"cross_references": {
    "xref_id": 170466478,
    "xref_name": "SID: 170466478",
    "xref_src": "PubChem"
}

=>

"cross_references": {
    "pubchem_sid": "170466478"
}

**Comment by newgene** [comment]
Solved now: http://mychem.info/v1/chem/CHEMBL170052?fields=chembl.xrefs

```
{
  "_id": "DXKRGNXUIRKXNR-UHFFFAOYSA-N",
  "chembl": {
    "_license": "http://bit.ly/2KAUCAm",
    "xrefs": {
      "pubchem": {
        "sid": 170466478
      }
    }
  }
}
```
