### ISSUE TITLE
drugcentral.drug_use.indication  List or not?

### ISSUE THREAD

**Issue by cbizon** [biothings/mychem.info#30]
for drugcentral.drug_use.indication and contraindication, if there is more than one indication, you get a list.  But if there is only one, then you don't get a list, you just get the item.   

That's fine, but in terms of parsing the output it means that you have to do a little extra logic.  From my perspective, it would be nicer to return a list of one item.

**Comment by newgene** [comment]
Need to check if this is solved in the recent data release. If not, should be done by next data release.

**Comment by newgene** [comment]
You can now add "always_list=drugcentral.drug_use.indication" to ensure this field returns a list.

See more info from https://github.com/biothings/mygene.info/issues/42 (the same implementation for MyGene.info)
