### ISSUE TITLE
website "docs" link points to myvariantinfo

### ISSUE THREAD

**Issue by buchanae** [biothings/mychem.info#31]
<img width="809" alt="screen shot 2018-08-16 at 9 37 17 am" src="https://user-images.githubusercontent.com/262647/44222954-0b540c00-a13b-11e8-86af-89c0b40a7c88.png">

**Comment by marcodarko** [comment]
We apologize for that, we are currently working on our documentation for MyChem.info, in the meantime we have removed those links and will restore them with the appropriate urls as soon as they become available .  Thank you for letting us know.
