### ISSUE TITLE
Mychem next release (ES6, parsers, etc...)

### ISSUE THREAD

**Issue by sirloon** [biothings/mychem.info#32]
- drugcentral collection was updated, new structure => run inspector for new mapping (done in 501a9a105f9681dc352584ce531abcdd1a15aff9)
- sider: use keylookup decorator to convert pubchem ID to InchiKey + rerun mapping generation (parser has changed ?) : mapping done in 67a449d46681670dd81b8d3e9d8717de9afb4996 (not keylookup)

**Comment by kevinxin90** [comment]
drugbank: add prefix for CHEBI xref
chembl: add prefix for CHEBI xref

**Comment by kevinxin90** [comment]
Fixed 'drugbank CHEBI' in 5caaa6410962ac063fbbcf32e198e7d2947466ff
Fixed 'chembl CHEBI' in 5131c420cfc37e9a30f6043954b111432e994229
