### ISSUE TITLE
PharmGKB data license changed to CC-BY-SA

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#34]
TODO:
    * update the license text for pharmgkb data source
    * see if any additional data we can include

**Comment by newgene** [comment]
data download: https://www.pharmgkb.org/downloads

@sirloon: please add `"license": "CC BY-SA 4.0"` to pharmgkb metadata entry.

**Comment by sirloon** [comment]
@newgene done 532e47d29eaf5f0bddc9c2a71a4d72e28749bd01
