### ISSUE TITLE
new data source: RHEA

### ISSUE THREAD

**Issue by andrewsu** [biothings/mychem.info#37]
main page is at https://www.rhea-db.org/.  provides useful information on chemical reactions (mapped to chebi IDs)

Many possible formats on their download page, but will need some work to figure out which is the right one to use.

**Comment by andrewsu** [comment]
This data source would be useful for tackling the query in https://github.com/NCATSTranslator/testing/issues/169.

Additional notes
* Rhea is CC-BY, so need to add the appropriate license link
* could be implemented as mychem plugin of a new associations-style API on pending.  *but*, rhea reactions have multiple inputs (reactants) and multiple outputs (products) so not sure if that fits cleanly into an associations-based API

**Comment by erikyao** [comment]
## Option 1 of Doc Structures

```json
{
  "_id": "rhea:12345",
  "EC": "12.3.4",
  "reactions": [{"_id": "chebi:98765", "name": "adenosine"}]
  "products": [...]
}
```

## Option 2 of Doc Structures

```json
{
  "_id": "chebi:12345",
  "reactions": [{"rhea:12345":{"chebi:98765", "chebi:88888"}}]
}
```

**Comment by erikyao** [comment]
- RHEA API is published to Pending.API: https://pending.biothings.io/rhea
- Samples of documents can be found at https://gist.github.com/erikyao/035175bf626d8f9469afc9da7c556e6e
- The plugin repo is https://github.com/biothings/Rhea

**Comment by andrewsu** [comment]
Given that @colleenXu also [annotated this API in SmartAPI](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/rhea/smartapi.yaml), going to close this issue.  (Note that rhea was implemented as a new pending API rather than as a new source for mychem.info...  This ticket can be reopened or cloned if we ever wanted to consider the mychem.info option again.)
