### ISSUE TITLE
New data source: Guide to Pharmcology

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#40]
http://www.guidetopharmacology.org/download.jsp

CC-BY-SA

**Comment by kevinxin90** [comment]
Seems that DGIdb integrate this database. http://dgidb.org/sources. (If we plan to integrate DGIdb)
Need double check on that.

**Comment by NeuralFlux** [comment]
Should I create the new parser in `src/plugins`? @newgene

**Comment by newgene** [comment]
@NeuralFlux let's create it as a standalone data plugin for now. It can be hosted at your own github account. We will decide later whether it's ready to be merged into MyChem.info or will be deployed as a standalone API first.
