### ISSUE TITLE
Issues with Drug bank

### ISSUE THREAD

**Issue by kevinxin90** [biothings/mychem.info#5]
1. Fields documented in the mapping file but returning zero hit:
drugbank.pharmacology.snp_effects.effects.rs-id
drugbank.pharmacology.snp_effects.effects.gene-symbol
...and many others

2. Missing 'gene_name' field
Take an example of Maraviroc, a CCR5-targeted drug
https://www.drugbank.ca/drugs/DB04835#targets
Above is the link to this drug annotation information provided by drugbank website,
there is a field called 'Gene Name' in the table, however, that field is missing in c.biothings.io

**Comment by newgene** [comment]
@kevinxin90 Let's verify these issues in the current release, to see if anything still need to be fixed

**Comment by kevinxin90** [comment]
"targets" fields under "drugbank" is still missing some important information, including "gene-name", "references" (the pubmed-id information under it).
Proposed new structure for "targets" field (taking example of http://mychem.info/v1/chem/DBEPLOCGEIEOCV-WSBQPABSSA-N?fields=drugbank.targets):
  {
        "actions": "inhibitor",
        "general_function": "Sterol 5-alpha reductase activity",
        "id": "BE0000585",
        "known_action": "yes",
        "name": "3-oxo-5-alpha-steroid 4-dehydrogenase 2",
        "organism": "Human",
        "source": "Swiss-Prot",
        "specific_function": "Converts testosterone (T) into 5-alpha-dihydrotestosterone (DHT) and progesterone or corticosterone into their corresponding 5-alpha-3-oxosteroids. It plays a central role in sexual differentiation and androgen physiology.",
        "uniprot": "P31213",
        **"gene_name": "SRD5A2",**
        **"pmids": [12773767, 16818707, 12670724, ...]**
      }

**Comment by kevinxin90** [comment]
@greg-k-taylor The issue regarding the first item "drugbank.pharmacology" is already taken care of. Only need to deal with the second one regarding "targets"

**Comment by sirloon** [comment]
- todo: merge this PR https://github.com/biothings/mychem.info/pull/59
- update mapping for the 2 new fields
