### ISSUE TITLE
add /metadata and /metadata/fields to the query examples section

### ISSUE THREAD

**Issue by newgene** [biothings/mychem.info#60]
Add this to the landing page query examples section at the bottom:

Get data source metadata:
GET http://mychem.info/metadata

Get the list of all fields:
GET http://mychem.info/metadata/fields

This applicable to mygene.info and myvariant.info APIs as well.

**Comment by marcodarko** [comment]
Added metadata examples and fields examples, should work on both https and http like others. Also fixed typo on myChem.
