### ISSUE TITLE
Fields with Mixed Type

### ISSUE THREAD

**Issue by kevinxin90** [biothings/mychem.info#61]
The following fields need to be fixed in the parser level to conform to the same data type

7. drugcentral.drug_use.indication.snomed_concept_id: int/float -> int (should be int, need to look at why it's float in some cases)

**Comment by kevinxin90** [comment]
17. aeolus.outcomes.prr_95_ci: None/number -> remove none
18. aeolus.outcomes.ror_95_ci: None/number -> remove none

**Comment by kevinxin90** [comment]
Regarding the first comment: "drugcentral.drug_use.indication.snomed_concept_id: int/float -> int", it's fixed in commit c3b92b97732097fd821cd6bcb0273543d62d2bb9

**Comment by kevinxin90** [comment]
aeolus data has been fixed in the mongodb database. New collection name: aeolus_201903_fix_none. @sirloon

**Comment by sirloon** [comment]
collection integrated in prod db
