### ISSUE TITLE
Data issue? Stange result imatinib KTUFNOKKBVMGRW-UHFFFAOYSA-N

### ISSUE THREAD

**Issue by iainmwallace** [biothings/mychem.info#68]
Hi,

I was just exploring the demo api page and got a strange result when I ran this query:
 curl -X GET "http://mychem.info/v1/query?q=KTUFNOKKBVMGRW-UHFFFAOYSA-N" -H "accept: application/json"

It is the inchikey for Imatinib, an ABL1/BCR drug https://pubchem.ncbi.nlm.nih.gov/compound/Imatinib

The data returned appear to be for this inchikey instead VGIVLIHKENZQHQ-UHFFFAOYSA-N
This query gives an identical response to the imatinib query
curl -X GET "http://mychem.info/v1/query?q=VGIVLIHKENZQHQ-UHFFFAOYSA-N" -H "accept: application/json"

Thanks

Iain

**Comment by kevinxin90** [comment]
@iainmwallace 
Hi Iain, when you are querying MyChem.info using the syntax of "http://mychem.info/v1/query?q=*", you are essentially using the full text query feature. And the hyphen in InChi Key appears to be a special character in full text query. Thus it will return you more results (some results are partial matches) than you want.

If you would like to query by InChiKey, the most convenient way is to use our "http://mychem.info/v1/chem/" endpoint, for example, http://mychem.info/v1/chem/KTUFNOKKBVMGRW-UHFFFAOYSA-N. This will return you the exact match. You could also query by a specific field (query by pubchem InChiKey field), for example, http://mychem.info/v1/query?q=pubchem.inchi_key:KTUFNOKKBVMGRW-UHFFFAOYSA-N. Both queries should return you the same results.

We currently don't have detailed documentation for MyChem.info. But you could refer to our documentation for MyGene.info (a sibling API of MyChem.info with a focus on genes) for how to query BioThings APIs.

**Comment by iainmwallace** [comment]
Ah! Thanks so much for the clarification, that makes a lot of sense. 

In retrospect, I was confused because the example in the text box of the try it out feature of the query field is an inchikey. Perhaps in a future release it might make sense to change this default option to something else.

Thanks again for the quick response.

**Comment by kevinxin90** [comment]
Thanks! I saw the example part you are referring to. We will fix it soon!
