### ISSUE TITLE
pubchem parser consumes too much memory

### ISSUE THREAD

**Issue by sirloon** [biothings/mychem.info#76]
This prevents pubchem from being updated. After 15-30min uploading, some processes takes a lot of memory (one process takes care of one file input, so it may be specific to some data file. to be confirmed).

![image](https://user-images.githubusercontent.com/2883770/72006995-9c7ec380-3205-11ea-9c0c-a82233239f72.png)

**Comment by sirloon** [comment]
listing pubchem xml files shows huge increase in file size starting in November 2019 (also last time we could upload the data). Some files are >1GiB compressed, but this call (as far as I can tell), brings everything in memory:

https://github.com/biothings/mychem.info/blob/master/src/hub/dataload/sources/pubchem/pubchem_parser.py#L14

```
-rw-rw-r-- 1 mychem mychem  3.4M Nov 12 11:28 Compound_078475001_078500000.xml.gz
-rw-rw-r-- 1 mychem mychem   66M Nov 12 11:28 Compound_053375001_053400000.xml.gz
-rw-rw-r-- 1 mychem mychem  5.8M Nov 12 11:28 Compound_076000001_076025000.xml.gz
-rw-rw-r-- 1 mychem mychem   62M Nov 12 11:28 Compound_070475001_070500000.xml.gz
-rw-rw-r-- 1 mychem mychem  8.2M Nov 12 11:28 Compound_075975001_076000000.xml.gz
-rw-rw-r-- 1 mychem mychem  6.3M Nov 12 11:29 Compound_077150001_077175000.xml.gz
-rw-rw-r-- 1 mychem mychem  5.6M Nov 12 11:29 Compound_091975001_092000000.xml.gz
-rw-rw-r-- 1 mychem mychem   64M Nov 12 11:29 Compound_139575001_139600000.xml.gz
-rw-rw-r-- 1 mychem mychem   59M Nov 12 11:30 Compound_071650001_071675000.xml.gz
-rw-rw-r-- 1 mychem mychem   48M Nov 12 11:30 Compound_021875001_021900000.xml.gz
-rw-rw-r-- 1 mychem mychem   77M Nov 12 11:31 Compound_139025001_139050000.xml.gz
-rw-rw-r-- 1 mychem mychem  1.4G Nov 23 19:41 Compound_003500001_004000000.xml.gz
-rw-rw-r-- 1 mychem mychem  1.4G Nov 23 19:44 Compound_004500001_005000000.xml.gz
-rw-rw-r-- 1 mychem mychem  1.3G Nov 23 20:06 Compound_008500001_009000000.xml.gz
-rw-rw-r-- 1 mychem mychem  1.3G Nov 23 20:06 Compound_008000001_008500000.xml.gz
-rw-rw-r-- 1 mychem mychem  1.5G Nov 23 20:34 Compound_010000001_010500000.xml.gz
-rw-rw-r-- 1 mychem mychem   25K Nov 23 21:32 Compound_050000001_050500000.xml.gz
-rw-rw-r-- 1 mychem mychem  1.2G Nov 23 22:07 Compound_055000001_055500000.xml.gz
-rw-rw-r-- 1 mychem mychem  1.4G Nov 23 22:13 Compound_055500001_056000000.xml.gz
-rw-rw-r-- 1 mychem mychem  1.4G Nov 23 22:13 Compound_056000001_056500000.xml.gz
[... then most/all files are >1GiB]
```

**Comment by newgene** [comment]
Supposedly, this line:
https://github.com/biothings/mychem.info/blob/master/src/hub/dataload/sources/pubchem/pubchem_parser.py#L15

should be in the [streaming mode](https://github.com/martinblech/xmltodict#streaming-mode) already, but probably not working as expected (`item_depth=2` changed?). Or this line works in the streaming mode, but the rest of `load_data` function did not carry through the streamed data properly?

**Comment by sirloon** [comment]
@newgene I didn't dig the parser much, that was a guess (for read() to RAM). It was mostly about the file size changes over time, it definitely relates to our problem. Also maybe it means more docs, that would be a big index size increase too

**Comment by kevinxin90** [comment]
@polyg314 When you're working on this issue let's also try to evaluate if we can extract other useful association info from the XML file (e.g. those available in pubchem website: https://pubchem.ncbi.nlm.nih.gov/compound/2244)

**Comment by polyg314** [comment]
Issue resolved in following pull request: 

https://github.com/biothings/mychem.info/pull/85

**Comment by ravila4** [comment]
Issue further resolved in https://github.com/biothings/mychem.info/pull/109
