### ISSUE TITLE
table of "Available fields" not rendering correctly

### ISSUE THREAD

**Issue by andrewsu** [biothings/mychem.info#84]
https://docs.mychem.info/en/latest/doc/data.html#available-fields is not rendering correctly (see screenshot below).  Likely related to https://github.com/biothings/mygene.info/issues/88

![image](https://user-images.githubusercontent.com/2635409/94185615-613b2800-fe5a-11ea-84ad-44cea88030e8.png)

**Comment by newgene** [comment]
yep, same issue as described in https://github.com/biothings/mygene.info/issues/88. Fixed in https://github.com/biothings/mychem.info/commit/a0f29d9797c44dca930df0355f6f86767af7b293.
